server:
  servlet:
    context-path: /files
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
    basedir: logs
  port: 8080

logging:
  config: classpath:log4j2-spring.xml

spring:
  profiles:
    active: @profileActive@
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

